version: "3.8"
services:
  db:
    build: .
    container_name: db
    restart: always
    image: postgres:16.0-alpine3.18
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME

  go-server:
    build: .
    container_name: go_server
    command: sh -c "go install && rss-aggregator"
    volumes:
      - .:/code
    ports:
      - $PORT:$PORT
    depends_on:
      - db
    env_file: .env

volumes:
  postgres-db: